### ISSUE TITLE
why is Gateway Load Balancer working on OSI layer 3 while uses layer 4 TCP port info?

### ISSUE THREAD

**Issue by oldpride** [awsdocs/elb-gateway-load-balancers-user-guide#2]
"A Gateway Load Balancer operates at the third layer of the Open Systems Interconnection (OSI) model, the network layer. It listens for all IP packets across all ports and forwards traffic to the target group that's specified in the listener rule. It maintains stickiness of flows to a specific target appliance using 5-tuple (for TCP/UDP flows) or 3-tuple (for non-TCP/UDP flows). "

Isn't TCP is a transport protocol on Layer 4? 
Should Gateway Load Balancer be called layer 4 balancer instead?

On the other hand, AWS Network Load Balancer is called layer 4 balancer, but it only uses IP info. Should AWS Network Load Balancer be called layer 3 balancer?

Thank you

**Comment by julieso** [comment]
I notice that the features page [1] says the load balancer type is "Layer 3 Gateway + Layer 4 Load Balancing". Is this clearer?

[1] https://aws.amazon.com/elasticloadbalancing/features/
